### PR TITLE
Update VBO with user requests

### LINKED ISSUE #65: Cat synonyms?
While attempting to map OMIA cat breeds to VBO, a question arose to do with synonyms:
Are the three "Non Recognized" entries (VBO:0100175, VBO:0100176, VBO:0100177) equivalent to "Domestic"? If so, can "Domestic" be entered as a synonym for each entry?

### LINKED ISSUE #164: Error in label and synonym of VBO:0005306?
Hi,

VBO:0005306 has label `-, Turkey (Cattle)` and synonym `-`.
Presumably the `-` stands for something?

Thanks,

Paola

### LINKED ISSUE #188: New entry for VBO 'Rangeland Goats'
For new term requests, please provide the following information:

Dear Katie,

I couldn't find Rangeland goats in VBO - sorry if it is there and I missed it:

## Preferred term label
Rangeland (goats)

## Suggested parent term

Goat / capra hircus

## Source
https://www.goatindustrycouncil.com.au/goats-in-australia/rangeland-goats/ 👍 The rangeland goat is a composite breed of goat which has become naturalised throughout Australia’s rangelands and in other areas which offer natural protection against predators. These goats have effectively adjusted to the environment to the extent that they no longer bear any strong resemblance to the original breeds of domesticated goats introduced with European settlement.

If you would like a nanoattribution, please indicate your ORCID id

### LINKED ISSUE #189: Add synonym to http://purl.obolibrary.org/obo/VBO_0009377
Dear Katie,

please add 'Australian Brown' as synonym to Australian All Brown, Australia (Goat) - VBO:0009377

Source: https://dairygoats.org.au/dairy-goat-breeds/australian-brown/

Regards,

Imke

### LINKED ISSUE #195: Additional cat breeds
Dear Katie,

the following reference
Jaito W, Singchat W, Patta C, Thatukan C, Kumnan N, Chalermwong P, Budi T, Panthum T, Wongloet W, Wattanadilokchatkun P, Thong T, Muangmai N, Han K, Duengkae P, Phatcharakullawarawat R, Srikulnath K. Shared alleles and genetic structures in different Thai domestic cat breeds: the possible influence of common racial origins. Genomics Inform. 2024 Jul 31;22(1):12. doi: 10.1186/s44342-024-00013-4. PMID: 39085978; PMCID: PMC11292921.

lists cat breeds that I could not find having a quick look at VBO
- Wichien Maat (WCM) and  Konja (KJ) 
- Khao-Manee may need to be added as synonym for Khao Manee (KM)

Regards,

Imke

### LINKED ISSUE #198: Term request - pigeon
Dear Katie,

please add the following pigeon breeds: 

Taihu Dianzi
Tarim

Parent: Columba livia

Source: PMID:38612286 (https://pubmed.ncbi.nlm.nih.gov/38612286)

### LINKED ISSUE #199: Term request - chicken
Dear Katie, 

Can we please add the following breed to VBO:

Bamaxiaogu (chicken)
parent: Gallus gallus
Source: Huang L, Guo Q, Sun J, Wang Z, Jiang Y, Chang G, Bai H. New findings on the genetic basis of feathered legs in chickens:association of CUBN gene mutations with feathered leg phenotype. J Anim Sci. 2024 Aug 27:skae252. doi: 10.1093/jas/skae252. Epub ahead of print. PMID: 39187978.

Thank you

### LINKED ISSUE #200: Update GCCF and FIFe URLs/breed recognition status/breed codes for cat breeds
Update:
1. GCCF and FIFe URLs are not correct and need to be updated.

FIFe change from http://fifeweb.org/wp/breeds/breeds_prf_stn.php to https://fifeweb.org/cats/ems-system/
GCCF changed from https://www.gccfcats.org/wp-content/uploads/2022/04/SOP.final_.February2022.pdf to https://www.gccfcats.org/wp-content/uploads/2024/04/SOP.final_.April2024.pdf

3. Some breed registration statuses have changed for these organizations:
GCCF full status for Chartreux, Nebelung

5. FIFe non recognized breeds should have "non" after the breed code.

### PR DESCRIPTION
**Pull request by katiermullen**
- Address #181  - add DSH and Japanese domestic cat 
- Close #195 - additional cat breed synonyms
- Close #200 - update FIFe and GGCF URLs, breed codes 
- Close #189 - add syn Australian Brown (Goat)
- Close #198 - two new pigeon breeds
- Close #199 - add one new chicken breed
- Close #65 - Add mixed breed cat and children DSH/DLH/DMH, obsolete breed-registry specific terms that were out of scope 
- Close #188 - add new goat breed - Rangeland
- Close #164 - update label for -, Turkey (Cattle)

### CODE REVIEW

**Comment by katiermullen** [comment]
@sabrinatoro please review at your convenience. Not urgent. I just wanted to get the PR submitted so it is not hanging over me :) Instead it is hanging over you :)

**Review by sabrinatoro — CHANGES_REQUESTED** [review]
@katiermullen 
This is fantastic! And it is a ton of work. Thank you!!!! 
I only have one comment.
It looks like the following breed registration status was not updated for Nebelung (GCCF organization now says it is fully recognized). (from https://github.com/monarch-initiative/vertebrate-breed-ontology/issues/200)
See ontology screenshot from this PR: 
Screenshot 2024-10-14 at 4 50 12 PM

**Comment by katiermullen** [comment]
@sabrinatoro I have updated this PR with your requested change. Thank you for catching my mistake!

**Review by sabrinatoro — APPROVED** [review]
Looks good! Thank you @katiermullen. 
Approving and merging.

**Pull request merged**
