### PR TITLE
update vbo with the new components

### PR DESCRIPTION
**Pull request by sabrinatoro**
In this PR, the components were updated with the new (updated and improved) google spreadsheets.

@matentzn : I am unable to create the component for dadisbreedcountry.owl
- all the other components seem ok (and they all share the same spreadsheet format)
- The error message is: 
INVALID ONTOLOGY FILE ERROR Could not load a valid ontology from file: dadisbreedcountry.owl

The only thing different with that file is the WIKIDATA information. 
Is this issue something "easy" you can point me to? (if not, I will ask at our next 1:1)
Thanks!

### CODE REVIEW

**Comment by sabrinatoro** [comment]
Note: there is a detailed log (which is long). The problem is with the parser. (how do I communicate this long report?)
I suspect the issue is weird characters in the "description of origin" column. But this was not a problem in the old spreadsheet, so I don't know whether it is that or not.

**Comment by matentzn** [comment]
description of origin seems to be `AI` in the robot template, not `A` (what it should be). Can you check?

**Comment by sabrinatoro** [comment]
> description of origin seems to be AI in the robot template, not A (what it should be). Can you check?

I saw that and I updated it. But I still get the same error.

**Comment by matentzn** [comment]
running with -B?

**Comment by matentzn** [comment]
pushed some updated files, seems no errors

**Comment by katiermullen** [comment]
@sabrinatoro I addressed the 5 violations in the QC check in the Google Sheets. 

I still need to add the remaining dog breeds for obsoletion.

**Comment by sabrinatoro** [comment]
@katiermullen 
VBO:0000662 was the parent for VBO:0007986, but I cannot find any record for VBO:0000662. Do you know/remember where that ID might come from? Thank you!

**Comment by katiermullen** [comment]
VBO:0000662 is "Danish White Spitz (Dog)" - source is DAD-IS. I see that there is an error (that I likely made) when I moved the DAD-IS dog transboundary breeds to the dog spreadsheet. "Danish White Spitz (Dog)" was reassigned a new VBO ID = VBO:0200434 (incorrectly). Please let me know how to resolve.

**Comment by sabrinatoro** [comment]
This PR is old. A new one was created and merged

**Pull request closed without merging**
